server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  cloud:
    config:
      import-check:
        enabled: false
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  main:
    banner-mode: off
  config:
    import: configserver:http://localhost:8085