server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  cloud:
    config:
      import-check:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    banner-mode: off

  config:
    import: configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true