spring:
  application:
    name: RATING-SERVICE
  cloud:
    config:
      import-check:
        enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Microservices
server:
  port: 8083