spring:
  application:
    name: RATING-SERVICE
  cloud:
    config:
      import-check:
        enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Microservices
  config:
    import: configserver:http://localhost:8085
server:
  port: 8083