server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ankush-Paul-02/Microservices
          clone-on-start: true
  main:
    banner-mode: off